#!/usr/bin/env python3
"""
Generate a C++ source file mapping requested engine symbols to (mangled name,
file offset) pairs. The runtime adds the main-exe load base to compute real
addresses.

Usage:
  gen_symbols.py --binary <factorio> --output <file.cpp> --filter <patterns.txt>
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--binary", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--filter", required=True, type=Path)
    return ap.parse_args()


def load_filters(path: Path) -> list[str]:
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line)
    return out


def collect_symbols(binary: Path, patterns: list[str]) -> list[tuple[str, str, int]]:
    """Returns list of (demangled, mangled, offset) for symbols matching any pattern."""
    # nm with both mangled and demangled in parallel: use --format=posix and run twice.
    mangled = subprocess.check_output(
        ["nm", "--defined-only", "--format=bsd", str(binary)],
        text=True, errors="replace")
    demangled = subprocess.check_output(
        ["nm", "--defined-only", "--demangle", "--format=bsd", str(binary)],
        text=True, errors="replace")

    # Match line by line. nm bsd format: "<addr> <type> <name>"
    line_re = re.compile(r"^([0-9a-f]+)\s+([A-Za-z])\s+(.+)$")
    mangled_lines = mangled.splitlines()
    demangled_lines = demangled.splitlines()
    if len(mangled_lines) != len(demangled_lines):
        print("warning: nm mangled/demangled line counts differ "
              f"({len(mangled_lines)} vs {len(demangled_lines)})", file=sys.stderr)

    out: list[tuple[str, str, int]] = []
    seen: set[str] = set()
    for ml, dl in zip(mangled_lines, demangled_lines):
        mm = line_re.match(ml)
        dm = line_re.match(dl)
        if not (mm and dm):
            continue
        addr_hex, sym_type, mangled_name = mm.group(1), mm.group(2), mm.group(3)
        _, _, demangled_name = dm.group(1), dm.group(2), dm.group(3)
        if sym_type not in "TtWwiu":
            continue
        if not any(p in demangled_name for p in patterns):
            continue
        if mangled_name in seen:
            continue
        seen.add(mangled_name)
        out.append((demangled_name, mangled_name, int(addr_hex, 16)))
    return out


def emit_cpp(symbols: list[tuple[str, str, int]], output: Path) -> None:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by gen_symbols.py — do not edit by hand.")
    lines.append("#include \"factorio_symbols.hpp\"")
    lines.append("")
    lines.append("namespace factorio_hooks {")
    lines.append("")
    lines.append(f"const SymbolEntry kSymbolTable[] = {{")
    for demangled, mangled, offset in symbols:
        # Escape any backslash/quote in the demangled signature.
        demangled_escaped = demangled.replace("\\", "\\\\").replace('"', '\\"')
        mangled_escaped = mangled.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'  {{"{demangled_escaped}", "{mangled_escaped}", 0x{offset:x}}},')
    lines.append("};")
    lines.append(f"const std::size_t kSymbolTableSize = "
                 f"sizeof(kSymbolTable) / sizeof(kSymbolTable[0]);")
    lines.append("")
    lines.append("} // namespace factorio_hooks")
    output.write_text("\n".join(lines) + "\n")


def main() -> int:
    args = parse_args()
    patterns = load_filters(args.filter)
    if not patterns:
        print("no patterns in filter file", file=sys.stderr)
        return 1
    syms = collect_symbols(args.binary, patterns)
    print(f"matched {len(syms)} symbols across {len(patterns)} patterns",
          file=sys.stderr)
    if not syms:
        print("no symbols matched any pattern; check spelling", file=sys.stderr)
        return 1
    emit_cpp(syms, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
